### ISSUE TITLE
Expanded deployment options

### ISSUE THREAD

**Issue by cnkcb** [github/copilot-survey-engine#16]
Deploying locally in our corporate Azure is extremely onerous, time consuming and expensive.  A hosted option would be preferable.  Better still, a deployment with SQLite on Glitch.

**Comment by mageroni** [comment]
Hi @cnkcb, as long as it is a SQL based engine it will be compatible with the app. The instructions for doing the deployment on Azure are available just as an optional deployment choice. But feel free to do the deployment with SQLite and contribute back in a Pull Request, so other users can have your guide as a reference. I'll close this issue for now, but don't hesitate to reopen it if you'd like to comment something else.
