### ISSUE TITLE
Feature request: add the ID of the PR in the issue title

### ISSUE THREAD

**Issue by ghsioux** [github/copilot-survey-engine#3]
Hello team,
Currently all the issue opened by the bot have the same title `Copilot Usage`. Adding the ID of the associated PR (e.g. `Copilot Usage - PR#33`) might be a small improvement to not get lost into the multiple opened/closed issues.

**Comment by mageroni** [comment]
That's a great request @ghsioux!! Originally the thought was maintaining the same name for the sake of homogeneity. I received no objection from the current users towards this change, so I'll proceed and merge the pull request
