### ISSUE TITLE
Cognitive service and insights not optional

### ISSUE THREAD

**Issue by ChaiSwaddipong** [github/copilot-survey-engine#9]
The setup instructions indicate that Azure Cognitive Services and Application Insights are optional. However, when I clicked on the Deploy to Azure button, the Azure Portal required all boxes to be filled out. There is no way around it,

**Comment by ChaiSwaddipong** [comment]
![surveytoolerror](https://github.com/mageroni/copilot-survey-engine/assets/81920890/f51c9995-52a5-4fb0-be12-cc5996c5b2e5)

**Comment by ChaiSwaddipong** [comment]
I found a workaround. One would need to edit the template. I think it would help to add another Deploy to Azure button tied to a template without the mentioned optional services

**Comment by mageroni** [comment]
Thanks for sharing @ChaiSwaddipong!! I have updated the ARM Template so it defaults to these values being optional. I'll close this issue as completed but please feel free to reopen it if you have additional feedback.
